#!/bin/sh

# folder on ting pen
if [ -e "/run/media/$USER/Ting/"'$ting' ]; then
	OpenSuse 42/15
	tingf="/run/media/$USER/Ting/"'$ting'
elif [ -e 'Volumes/Ting' ]; then
	# Mac OS
	tingf="Volumes/Ting/"'$ting'
else
	echo 'Ting pen not mounted.'
	exit 1
fi
#tingf=~/Downloads/ting

# common url components
PRE=http://13.80.138.170/book-files
SN=sn/5497559973888/
POST=area/en/$SN

while read idlf; do
    lid=`echo $idlf | perl -pe 's/([\n\r])//g'`
    id=`echo $lid | perl -pe 's/(^0+)//g'`

    echo "Output: $tingv, buch-id: $lid, short-id: $id"
    wget $PRE/get-description/id/$id/$POST -O $tingf/"$lid"_en.txt
    wget $PRE/get/id/$id/type/thumb/$POST -O $tingf/"$lid"_en.png
    wget $PRE/get/id/$id/area/en/type/archive/$SN -O $tingf/"$lid"_en.ouf
done <"$tingf/TBD.TXT"

# desktop notification
command -v notify-send Ting 'Book downloading finished. Please unmount pen.'
